### ISSUE TITLE
关于改变SGPageTitle字的颜色，和指示器颜色

### ISSUE THREAD

**Issue by Owl7** [kingsic/SGPagingView-Swift#1]
请问一下，你这个改变pageTitle字的颜色和指示器的颜色，我看你这个是在初始化PageTitleView的时候通过配置来改变颜色，那如果我第一次创建好了后面要改变颜色怎么办？难道每次都要去重新创建么？很疑惑，不应该是设计成创建一次，后面不论什么时候想改颜色就改吗？还是我没找到？请大神指点。

**Comment by Owl7** [comment]
我的做法是这样
// MARK: - layoutSubviews
    override func layoutSubviews() {
        super.layoutSubviews()
        
        self.setupSubviews()
        P_btn_action(button: btnMArr[index])
    }
把设置视图放在layoutSubviews里面！请问你有对代码这方面的改进的计划么？

**Comment by kingsic** [comment]
切记不要这样搞，后期我会根据你的业务需求来添加对应的方法（layoutSubviews 的调用时机请百度自补） @Owl7
