### ISSUE TITLE
关于循环引用

### ISSUE THREAD

**Issue by MuRanJiangXia** [kingsic/SGPagingView-Swift#9]
SGPageViewPopGestureVC 中
    private var _delegate: UIGestureRecognizerDelegate? = nil

会造成循环引用 

建议改成 
   weak private var _delegate: UIGestureRecognizerDelegate? = nil

**Comment by Xue765** [comment]
最后，加weak了吗？

**Comment by Xue765** [comment]
> SGPageViewPopGestureVC 中
> private var _delegate: UIGestureRecognizerDelegate? = nil
> 
> 会造成循环引用
> 
> 建议改成
> weak private var _delegate: UIGestureRecognizerDelegate? = nil

最后用 weak了吗？

**Comment by MuRanJiangXia** [comment]
> 最后，加weak了吗？

我加了
